import { Language, LanguageData, IjazahPrices } from './types';

export const LOCK_CHECK = true;
export const WHATSAPP_PHONE_NUMBER = "6289516841713";
export const LANGUAGES: Language[] = ['en', 'ar', 'id'];

export const IJAZAH_PRICES: IjazahPrices = {
    'Hafs \'an \'Asim': { 1: 149000, 2: 199000, 3: 249000, 4: 400000, 5: 450000, 6: 450000, 7: 799000 },
    'The Ten Recitations': { 1: 300000, 2: 399000, 3: 600000, 4: 800000, 5: 899000, 6: 960000, 7: 1100000 },
    'Different Qira\'ah': { 1: 300000, 2: 400000, 3: 500000, 4: 550000, 5: 600000, 6: 640000, 7: 700000 }
};

export const PATH_TRANSLATION_KEYS: { [key: string]: string } = {
    "Hafs 'an 'Asim": 'hafsButton',
    "The Ten Recitations": 'tenRecitationsButton',
    "Different Qira'ah": 'differentQiraahButton'
};


export const LANGUAGE_DATA: LanguageData = {
    'en': {
        headerTitle: "Maqrat Alrahman",
        title: "Course Registration",
        subtitle: "Secure your spot and start your learning journey.",
        nameLabel: "Full Name",
        sourceLabel: "How did you hear about us?",
        aboutLabel: "Tell us about yourself",
        phoneLabel: "WhatsApp Number",
        buttonText: "Register via WhatsApp",
        homeButtonText: "Home",
        registerButtonText: "Register",
        langButtonText: "AR",
        homePageTitle: "Welcome to Maqrat Alrahman",
        homePageSubtitle: "Exploring Islamic knowledge, together.",
        courseInfoText: "We are preparing insightful Islamic courses.",
        followUsText: "Registration will open when a new course is announced.",
        instagramLinkText: "Follow on Instagram",
        previousCoursesBtnHomepage: "View Past Courses",
        coursesTitle: "Our Past Courses",
        course3Text: "Advanced Tajwid",
        course4Text: "Fiqh of Worship",
        thanksMessage: "Thank You!",
        thanksText: "Your request has been submitted. We'll be in touch.",
        registerAnotherBtn: "Register Again",
        backToHome: "Back to Home",
        regClosedTitle: "Registration Closed",
        regClosedText: "There are no active courses now, please come back later.",
        regClosedButton: "Close",
        ijazahButtonText: "I want an Ijazah",
        ijazahTitle: "Embark on Your Ijazah Journey",
        ijazahSubtitle: "Connect your chain of transmission back to the Prophet (PBUH). Choose your path:",
        hafsButton: "Hafs 'an 'Asim",
        tenRecitationsButton: "The Ten Recitations",
        differentQiraahButton: "Different Qira'ah",
        quizTitle: "Ijazah Application",
        quizNameLabel: "Full Name:",
        quizAgeLabel: "Age:",
        quizFromLabel: "Country of Residence:",
        quizWeeklyLabel: "Weekly Reading Commitment:",
        quizSheikhLabel: "Have you previously studied with a Sheikh?",
        yes: "Yes",
        no: "No",
        quizJourneyLabel: "Briefly describe your journey with the Qur'an:",
        nextButton: "Next",
        paymentTitle: "Payment Information",
        paymentSubtitle: "Please confirm your selection to proceed.",
        ijazahSectionTitle: "Ijazah Program",
        ijazahSectionDesc: "Connect your chain of transmission.",
        tasmiSectionTitle: "Free Tasmi'",
        tasmiSectionDesc: "Recite your memorization to a teacher.",
        coursesSectionTitle: "Past Courses",
        coursesSectionDesc: "Explore our previously offered courses.",
        tasmiButtonText: "I want the free Tasmi'",
        tasmiQuizTitle: "Free Tasmi' Session",
        tasmiPortionLabel: "Juz' or Surah to Recite:",
        tasmiTimeLabel: "Preferred Time for Session:",
        submitButton: "Submit Request",
        tasmiFatihahOption: "Al-Fatihah",
        tasmiJuzAmmaOption: "Some of Juz Amma",
        tasmiSessionsLabel: "How many sessions you want:",
        tasmiInfoTitle: "What's Next?",
        tasmiInfoText1: "The teacher will choose the time and the date available for him.",
        tasmiInfoText2: "We will try to answer you as fast as we can.",
        paymentPriceText: "This will be:",
        payButton: "Send Your Request",
        bsiText: "You're one step away from starting your journey",
        summaryTitle: "Application Summary",
        summaryPath: "Ijazah Path",
        summaryCommitment: "Weekly Commitment",
        summaryPrice: "Price",
        monthlyText: "monthly",
        noteTitle: "Note:",
        noteText: "Scheduling is subject to the teacher's availability.",
        maxSessionsText: "Max 5 sessions",
        changeIjazahButton: "Change my Ijazah",
        youtubeLinkText: "Watch on YouTube",
        moderatorText: "This website is fully moderated by Yaman",
        daysPerWeek: "{count} days/week",
        ijazahPreviewCardTitle: "Ijazah Certificate",
        ijazahPreviewDesc: "View a sample of our Ijazah certificate.",
        ijazahPreviewButtonText: "Show me your Ijazah",
        ijazahPreviewTitle: "Ijazah Preview",
        ijazahSampleText: "This certificate of Ijazah connects the holder's chain of transmission (Sanad) for the recitation of the Holy Qur'an back to the Prophet Muhammad (Peace Be Upon Him). It is awarded to [Student Name] after demonstrating mastery in Tajwid and recitation before a qualified Sheikh.",
        tasmiInfoSectionTitle: "Important: About your Tasmi' Session",
        tasmiInfoSectionText: "Information about the Tasmi' session will be provided here. Please check back later for details.",
        continueButton: "Continue",
        backButton: "Back",
        ijazahInfoRequirementsTitle: "Ijazah Information and Requirements",
        ijazahInfoSectionTitle: "Important: About your Ijazah Program",
        ijazahInfoSectionText: "Each session will be approximately 10-20 minutes. We will begin by improving your Tajwid with Juz' Amma. Once proficiency is achieved, we will commence with the Ijazah. If your Tajwid is already perfect, we will begin the Ijazah program immediately.",
        quizTimeLabel: "What time do you want to read?",
        quizQiraahLabel: "Which Qira'ah do you want to learn?",
        scrollNote: "Scroll to see all days",
        timeSlot1: "5:10 AM - 5:50 AM",
        timeSlot2: "6:20 PM - 7:10 PM",
        timezoneNote: "(GMT+7 Jakarta Time)",
        quizLanguageLabel: "In which language do you want to learn?",
        langArabic: "Arabic",
        langEnglish: "English",
        langIndonesian: "Indonesian",
        summaryQiraah: "Preferred Qira'ah",
        summaryTime: "Preferred Time",
        summaryLanguage: "Language",
        ijazahTimeNoteTitle: "Ijazah required time:",
        ijazahTimeNoteHafs: "1 year and 5 months maximum.",
        ijazahTimeNoteTenRecitations: "1 year and 6 months to 2 years.",
        ijazahTimeNoteSpeed: "might be less, depends on your speed",
    },
    'ar': {
        headerTitle: "مقرأة الرحمن",
        title: "التسجيل في الدورة",
        subtitle: "احجز مكانك وابدأ رحلتك التعليمية.",
        nameLabel: "الاسم الكامل",
        sourceLabel: "كيف سمعت عنا؟",
        aboutLabel: "أخبرنا عن نفسك",
        phoneLabel: "رقم الواتساب",
        buttonText: "التسجيل عبر الواتساب",
        homeButtonText: "الرئيسية",
        registerButtonText: "تسجيل",
        langButtonText: "ID",
        homePageTitle: "أهلاً بكم في مقرأة الرحمن",
        homePageSubtitle: "نستكشف العلوم الإسلامية، معًا.",
        courseInfoText: "نحن بصدد إعداد دورات إسلامية نافعة.",
        followUsText: "سيفتح التسجيل عند الإعلان عن دورة جديدة.",
        instagramLinkText: "تابعنا على إنستغرام",
        previousCoursesBtnHomepage: "عرض الدورات السابقة",
        coursesTitle: "دوراتنا السابقة",
        course3Text: "تجويد متقدم",
        course4Text: "فقه العبادات",
        thanksMessage: "شكرًا لك!",
        thanksText: "لقد تم إرسال طلبك. سنتواصل معك قريبًا.",
        registerAnotherBtn: "تسجيل مرة أخرى",
        backToHome: "العودة للرئيسية",
        regClosedTitle: "التسجيل مغلق",
        regClosedText: "لا توجد دورات متاحة حاليًا، يرجى العودة لاحقًا.",
        regClosedButton: "إغلاق",
        ijazahButtonText: "أريد إجازة",
        ijazahTitle: "ابدأ رحلتك في الإجازة",
        ijazahSubtitle: "صِل سندك بالنبي صلى الله عليه وسلم. اختر طريقك:",
        hafsButton: "حفص عن عاصم",
        tenRecitationsButton: "القراءات العشر",
        differentQiraahButton: "قراءة مختلفة",
        quizTitle: "طلب الإجازة",
        quizNameLabel: "الاسم الكامل:",
        quizAgeLabel: "العمر:",
        quizFromLabel: "بلد الإقامة:",
        quizWeeklyLabel: "الالتزام الأسبوعي بالقراءة:",
        quizSheikhLabel: "هل درست سابقًا على شيخ؟",
        yes: "نعم",
        no: "لا",
        quizJourneyLabel: "صف بإيجاز رحلتك مع القرآن:",
        nextButton: "التالي",
        paymentTitle: "معلومات الدفع",
        paymentSubtitle: "يرجى تأكيد اختيارك للمتابعة.",
        ijazahSectionTitle: "برنامج الإجازة",
        ijazahSectionDesc: "صِل سندك.",
        tasmiSectionTitle: "تسميع مجاني",
        tasmiSectionDesc: "اسمع حفظك على معلم.",
        coursesSectionTitle: "الدورات السابقة",
        coursesSectionDesc: "تصفح دوراتنا المقدمة سابقًا.",
        tasmiButtonText: "أريد التسميع المجاني",
        tasmiQuizTitle: "جلسة تسميع مجانية",
        tasmiPortionLabel: "الجزء أو السورة للتسميع:",
        tasmiTimeLabel: "الوقت المفضل للجلسة:",
        submitButton: "إرسال الطلب",
        tasmiFatihahOption: "الفاتحة",
        tasmiJuzAmmaOption: "بعض من جزء عم",
        tasmiSessionsLabel: "كم عدد الجلسات التي تريدها:",
        tasmiInfoTitle: "ماذا بعد؟",
        tasmiInfoText1: "سيختار المعلم الوقت والتاريخ المتاح له.",
        tasmiInfoText2: "سنحاول الرد عليك في أسرع وقت ممكن.",
        paymentPriceText: "السعر سيكون:",
        payButton: "إرسال طلبك",
        bsiText: "أنت على بعد خطوة واحدة من بدء رحلتك",
        summaryTitle: "ملخص الطلب",
        summaryPath: "مسار الإجازة",
        summaryCommitment: "الالتزام الأسبوعي",
        summaryPrice: "السعر",
        monthlyText: "شهريًا",
        noteTitle: "ملاحظة:",
        noteText: "الجداول الزمنية تخضع لتوفر المعلم.",
        maxSessionsText: "5 جلسات كحد أقصى",
        changeIjazahButton: "تغيير إجازتي",
        youtubeLinkText: "شاهد على يوتيوب",
        moderatorText: "هذا الموقع بإشراف يمان بالكامل",
        daysPerWeek: "{count} أيام/أسبوع",
        ijazahPreviewCardTitle: "شهادة الإجازة",
        ijazahPreviewDesc: "شاهد عينة من شهادة الإجازة لدينا.",
        ijazahPreviewButtonText: "أرني إجازتكم",
        ijazahPreviewTitle: "معاينة الإجازة",
        ijazahSampleText: "هذه الشهادة إجازة تصل سند حاملها في تلاوة القرآن الكريم إلى النبي محمد (صلى الله عليه وسلم). تُمنح لـ [اسم الطالب] بعد إظهار الإتقان في التجويد والتلاوة أمام شيخ مجاز.",
        tasmiInfoSectionTitle: "هام: بخصوص جلسة التسميع",
        tasmiInfoSectionText: "سيتم توفير معلومات حول جلسة التسميع هنا. يرجى التحقق مرة أخرى لاحقًا للحصول على التفاصيل.",
        continueButton: "متابعة",
        backButton: "رجوع",
        ijazahInfoRequirementsTitle: "معلومات ومتطلبات الإجازة",
        ijazahInfoSectionTitle: "هام: بخصوص برنامج الإجازة",
        ijazahInfoSectionText: "مدة كل جلسة ستكون حوالي 10-20 دقيقة. سنبدأ بتحسين تجويدك مع جزء عم. بمجرد تحقيق الإتقان، سنبدأ بالإجازة. إذا كان تجويدك متقنًا بالفعل، فسنبدأ برنامج الإجازة على الفور.",
        quizTimeLabel: "ما الوقت الذي تريد أن تقرأ فيه؟",
        quizQiraahLabel: "أي قراءة تريد أن تتعلم؟",
        scrollNote: "مرر لرؤية كل الأيام",
        timeSlot1: "5:10 صباحًا - 5:50 صباحًا",
        timeSlot2: "6:20 مساءً - 7:10 مساءً",
        timezoneNote: "(توقيت جاكرتا GMT+7)",
        quizLanguageLabel: "بأي لغة تريد أن تتعلم؟",
        langArabic: "العربية",
        langEnglish: "الإنجليزية",
        langIndonesian: "الإندونيسية",
        summaryQiraah: "القراءة المفضلة",
        summaryTime: "الوقت المفضل",
        summaryLanguage: "اللغة",
        ijazahTimeNoteTitle: "الوقت المطلوب للإجازة:",
        ijazahTimeNoteHafs: "سنة و 5 أشهر كحد أقصى.",
        ijazahTimeNoteTenRecitations: "من سنة و 6 أشهر إلى سنتين.",
        ijazahTimeNoteSpeed: "قد تكون المدة أقل، يعتمد على سرعتك",
    },
    'id': {
        headerTitle: "Maqrat Alrahman",
        title: "Pendaftaran Kursus",
        subtitle: "Amankan tempat Anda dan mulailah perjalanan belajar Anda.",
        nameLabel: "Nama Lengkap",
        sourceLabel: "Dari mana Anda mengetahui tentang kami?",
        aboutLabel: "Ceritakan tentang diri Anda",
        phoneLabel: "Nomor WhatsApp",
        buttonText: "Daftar melalui WhatsApp",
        homeButtonText: "Beranda",
        registerButtonText: "Daftar",
        langButtonText: "EN",
        homePageTitle: "Selamat Datang di Maqrat Alrahman",
        homePageSubtitle: "Menjelajahi ilmu Islam, bersama.",
        courseInfoText: "Kami sedang mempersiapkan kursus-kursus Islami yang berwawasan.",
        followUsText: "Pendaftaran akan dibuka saat kursus baru diumumkan.",
        instagramLinkText: "Ikuti di Instagram",
        previousCoursesBtnHomepage: "Lihat Kursus Sebelumnya",
        coursesTitle: "Kursus-Kursus Kami Sebelumnya",
        course3Text: "Tajwid Lanjutan",
        course4Text: "Fikih Ibadah",
        thanksMessage: "Terima Kasih!",
        thanksText: "Permintaan Anda telah dikirim. Kami akan segera menghubungi Anda.",
        registerAnotherBtn: "Daftar Lagi",
        backToHome: "Kembali ke Beranda",
        regClosedTitle: "Pendaftaran Ditutup",
        regClosedText: "Saat ini tidak ada kursus aktif, silakan kembali lagi nanti.",
        regClosedButton: "Tutup",
        ijazahButtonText: "Saya ingin Ijazah",
        ijazahTitle: "Mulailah Perjalanan Ijazah Anda",
        ijazahSubtitle: "Sambungkan sanad Anda kembali ke Nabi (SAW). Pilih jalur Anda:",
        hafsButton: "Hafs 'an 'Asim",
        tenRecitationsButton: "Sepuluh Qira'at",
        differentQiraahButton: "Qira'at yang Berbeda",
        quizTitle: "Pendaftaran Ijazah",
        quizNameLabel: "Nama Lengkap:",
        quizAgeLabel: "Usia:",
        quizFromLabel: "Negara Tempat Tinggal:",
        quizWeeklyLabel: "Komitmen Bacaan Mingguan:",
        quizSheikhLabel: "Apakah Anda pernah belajar dengan seorang Syekh sebelumnya?",
        yes: "Ya",
        no: "Tidak",
        quizJourneyLabel: "Jelaskan secara singkat perjalanan Anda dengan Al-Qur'an:",
        nextButton: "Lanjutkan",
        paymentTitle: "Informasi Pembayaran",
        paymentSubtitle: "Harap konfirmasi pilihan Anda untuk melanjutkan.",
        ijazahSectionTitle: "Program Ijazah",
        ijazahSectionDesc: "Sambungkan sanad Anda.",
        tasmiSectionTitle: "Tasmi' Gratis",
        tasmiSectionDesc: "Setorkan hafalan Anda kepada seorang guru.",
        coursesSectionTitle: "Kursus Sebelumnya",
        coursesSectionDesc: "Jelajahi kursus yang pernah kami tawarkan.",
        tasmiButtonText: "Saya ingin Tasmi' gratis",
        tasmiQuizTitle: "Sesi Tasmi' Gratis",
        tasmiPortionLabel: "Juz' atau Surah yang akan Disetorkan:",
        tasmiTimeLabel: "Waktu yang Diinginkan untuk Sesi:",
        submitButton: "Kirim Permintaan",
        tasmiFatihahOption: "Al-Fatihah",
        tasmiJuzAmmaOption: "Sebagian dari Juz Amma",
        tasmiSessionsLabel: "Berapa sesi yang Anda inginkan:",
        tasmiInfoTitle: "Apa Selanjutnya?",
        tasmiInfoText1: "Guru akan memilih waktu dan tanggal yang tersedia untuknya.",
        tasmiInfoText2: "Kami akan mencoba menjawab Anda secepat mungkin.",
        paymentPriceText: "Totalnya:",
        payButton: "Kirim Permintaan Anda",
        bsiText: "Anda selangkah lagi untuk memulai perjalanan Anda",
        summaryTitle: "Ringkasan Pendaftaran",
        summaryPath: "Jalur Ijazah",
        summaryCommitment: "Komitmen Mingguan",
        summaryPrice: "Harga",
        monthlyText: "per bulan",
        noteTitle: "Catatan:",
        noteText: "Penjadwalan tergantung pada ketersediaan guru.",
        maxSessionsText: "Maks 5 sesi",
        changeIjazahButton: "Ubah Ijazah saya",
        youtubeLinkText: "Tonton di YouTube",
        moderatorText: "Situs web ini sepenuhnya dimoderasi oleh Yaman",
        daysPerWeek: "{count} hari/minggu",
        ijazahPreviewCardTitle: "Sertifikat Ijazah",
        ijazahPreviewDesc: "Lihat contoh sertifikat Ijazah kami.",
        ijazahPreviewButtonText: "Tunjukkan Ijazah Anda",
        ijazahPreviewTitle: "Pratinjau Ijazah",
        ijazahSampleText: "Sertifikat Ijazah ini menyambungkan sanad pemegangnya dalam tilawah Al-Qur'an hingga kepada Nabi Muhammad (SAW). Diberikan kepada [Nama Siswa] setelah menunjukkan penguasaan dalam Tajwid dan tilawah di hadapan seorang Syekh yang berkualifikasi.",
        tasmiInfoSectionTitle: "Penting: Tentang Sesi Tasmi' Anda",
        tasmiInfoSectionText: "Informasi tentang sesi Tasmi' akan diberikan di sini. Silakan periksa kembali nanti untuk detailnya.",
        continueButton: "Lanjutkan",
        backButton: "Kembali",
        ijazahInfoRequirementsTitle: "Informasi dan Persyaratan Ijazah",
        ijazahInfoSectionTitle: "Penting: Tentang Program Ijazah Anda",
        ijazahInfoSectionText: "Setiap sesi akan berdurasi sekitar 10-20 menit. Kita akan mulai dengan memperbaiki Tajwid Anda dengan Juz 'Amma. Setelah kemahiran tercapai, kita akan memulai Ijazah. Jika Tajwid Anda sudah sempurna, kita akan segera memulai program Ijazah.",
        quizTimeLabel: "Jam berapa Anda ingin membaca?",
        quizQiraahLabel: "Qira'at mana yang ingin Anda pelajari?",
        scrollNote: "Gulir untuk melihat semua hari",
        timeSlot1: "5:10 PAGI - 5:50 PAGI",
        timeSlot2: "6:20 SORE - 7:10 MALAM",
        timezoneNote: "(GMT+7 Waktu Jakarta)",
        quizLanguageLabel: "Dalam bahasa apa Anda ingin belajar?",
        langArabic: "Arab",
        langEnglish: "Inggris",
        langIndonesian: "Indonesia",
        summaryQiraah: "Qira'ah Pilihan",
        summaryTime: "Waktu Pilihan",
        summaryLanguage: "Bahasa",
        ijazahTimeNoteTitle: "Waktu yang dibutuhkan untuk Ijazah:",
        ijazahTimeNoteHafs: "Maksimal 1 tahun 5 bulan.",
        ijazahTimeNoteTenRecitations: "1 tahun 6 bulan hingga 2 tahun.",
        ijazahTimeNoteSpeed: "bisa jadi lebih cepat, tergantung kecepatan Anda",
    }
};