import { Language, LanguageData, IjazahPrices } from './types';

export const API_KEY = 'AIzaSyDYIxCWBClgnNT4rCyrwT3CDyL1ck_LZZ4';

export const LOCK_CHECK = true;
export const LANGUAGES: Language[] = ['en', 'ar', 'id'];

export const IJAZAH_PRICES: IjazahPrices = {
    'Hafs \'an \'Asim':    { 1: 40000, 2: 80000, 3: 120000, 4: 160000, 5: 200000, 6: 240000, 7: 280000 },
    'The Ten Recitations': { 1: 48000, 2: 92000, 3: 140000, 4: 188000, 5: 232000, 6: 280000, 7: 328000 },
    'Different Qira\'ah': { 1: 48000, 2: 92000, 3: 140000, 4: 188000, 5: 232000, 6: 280000, 7: 328000 }
};

export const TAJWID_IMPROVEMENT_PRICES: { [days: number]: number } = {
    15: 200000,
    10: 100000,
    5: 60000
};

export const PATH_TRANSLATION_KEYS: { [key: string]: string } = {
    "Hafs 'an 'Asim": 'hafsButton',
    "The Ten Recitations": 'tenRecitationsButton',
    "Different Qira'ah": 'differentQiraahButton'
};


export const LANGUAGE_DATA: LanguageData = {
    'en': {
        headerTitle: "Maqra'at Al-Huda",
        headerSubtitle: "By Qari Yaman Darwish",
        heroTitle: "Embark on Your Qur'anic Journey",
        heroSubtitle: "Master the sacred art of recitation and connect your lineage to the Prophet (ﷺ) through certified Ijazah programs, guided by Qari Yaman Darwish.",
        heroButton: "Start Your Journey",
        title: "Course Registration",
        subtitle: "Secure your spot and start your learning journey.",
        nameLabel: "Full Name",
        sourceLabel: "How did you hear about us?",
        aboutLabel: "Tell us about yourself",
        phoneLabel: "WhatsApp / Contact Number",
        whatsappLabel: "WhatsApp Number (make sure it's correct)",
        buttonText: "Submit Registration",
        homeButtonText: "Home",
        registerButtonText: "Register",
        langButtonText: "AR",
        homePageTitle: "Welcome to Maqra'at Al-Huda",
        homePageSubtitle: "Exploring Islamic knowledge, together.",
        courseInfoText: "We are preparing insightful Islamic courses.",
        followUsText: "Registration will open when a new course is announced.",
        instagramLinkText: "Follow on Instagram",
        previousCoursesBtnHomepage: "View Past Courses",
        coursesTitle: "Our Past Courses",
        course3Text: "Ayyuhal Walad",
        course4Text: "Tahsin Tilawah (Improving Recitation)",
        thanksMessage: "Thank You!",
        thanksText: "Your request has been submitted. We'll be in touch.",
        registerAnotherBtn: "Register Again",
        backToHome: "Back to Home",
        regClosedTitle: "Registration Closed",
        regClosedText: "There are no active courses now, please come back later.",
        regClosedButton: "Close",
        ijazahButtonText: "I want an Ijazah",
        ijazahTitle: "Embark on Your Ijazah Journey",
        ijazahSubtitle: "Connect your chain of transmission back to the Prophet (PBUH). Choose your path:",
        hafsButton: "Hafs 'an 'Asim",
        tenRecitationsButton: "The Ten Recitations",
        differentQiraahButton: "Different Qira'ah",
        quizTitle: "Ijazah Application",
        quizNameLabel: "Full Name:",
        quizAgeLabel: "Age:",
        quizFromLabel: "Country of Residence:",
        quizWeeklyLabel: "Weekly Reading Commitment:",
        quizSheikhLabel: "Have you previously studied with a Sheikh?",
        yes: "Yes",
        no: "No",
        quizJourneyLabel: "Briefly describe your journey with the Qur'an:",
        nextButton: "Next",
        paymentTitle: "Payment Information",
        paymentSubtitle: "Please confirm your selection to proceed.",
        ijazahSectionTitle: "Ijazah Program",
        ijazahSectionDesc: "Connect your chain of transmission.",
        tasmiSectionTitle: "Opened Tasmi'",
        tasmiSectionDesc: "Recite your memorization to a teacher.",
        coursesSectionTitle: "Past Courses",
        coursesSectionDesc: "Explore our previously offered courses.",
        aboutUsSectionTitle: "About Us",
        aboutUsSectionDesc: "Learn more about our mission and vision.",
        aboutUsButtonText: "Learn More",
        aboutUsPageTitle: "About Maqra'at Al-Huda",
        aboutUsPageText: "This website is the official platform for all our programs. Here you can:\n- Register for Ijazah programs in various Qira'at.\n- Sign up for dedicated 'Tahsin Tilawah' (Tajwid Improvement) sessions.\n- Request a free 'Tasmi'' (recitation review) session.\n- View our past courses and learn about our mission.",
        tasmiButtonText: "I want the opened Tasmi'",
        tasmiQuizTitle: "Opened Tasmi' Session",
        tasmiPortionLabel: "Juz' or Surah to Recite:",
        tasmiTimeLabel: "Preferred Time for Session:",
        submitButton: "Submit Request",
        tasmiFatihahOption: "Al-Fatihah",
        tasmiJuzAmmaOption: "Some of Juz Amma",
        tasmiWeeklyLabel: "How many sessions you want?",
        tasmiInfoTitle: "What's Next?",
        tasmiInfoText1: "The teacher will choose the time and the date available for him.",
        tasmiInfoText2: "We will try to answer you as fast as we can.",
        paymentPriceText: "This will be:",
        payButton: "Submit Application",
        bsiText: "You're one step away from starting your journey",
        summaryTitle: "Application Summary",
        summaryPath: "Ijazah Path",
        summaryCommitment: "Weekly Commitment",
        summaryPrice: "Price",
        monthlyText: "monthly",
        noteTitle: "Note:",
        noteText: "Scheduling is subject to the teacher's availability.",
        changeIjazahButton: "Change my Ijazah",
        youtubeLinkText: "Watch on YouTube",
        moderatorText: "This website is fully moderated by Yaman",
        daysPerWeek: "{count} days/week",
        ijazahPreviewCardTitle: "Ijazah Certificate",
        ijazahPreviewDesc: "View a sample of our Ijazah certificate.",
        ijazahPreviewButtonText: "Show me your Ijazah",
        ijazahPreviewTitle: "Ijazah Preview",
        ijazahSampleText: "This certificate of Ijazah connects the holder's chain of transmission (Sanad) for the recitation of the Holy Qur'an back to the Prophet Muhammad (Peace Be Upon Him). It is awarded to the student after completing the memorization of the Holy Qur'an by heart and demonstrating mastery in Tajwid and recitation before a qualified Sheikh.",
        ijazahGrantText: "By the grace of Allah, my master Sheikh Ahmed Al-Kanas granted me Ijazah in the Ten Minor Mutawatir Qira'at from the Messenger of Allah (PBUH).\n\nIn the mosque of Imam Al-Shafi'i University on the night of the seventeenth of Ramadan,\nCorresponding to: March 25, 2024",
        tasmiInfoSectionTitle: "Important: About your Tasmi' Session",
        tasmiInfoSectionText: "Information about the Tasmi' session will be provided here. Please check back later for details.",
        continueButton: "Continue",
        backButton: "Back",
        ijazahInfoRequirementsTitle: "Ijazah Information and Requirements",
        ijazahInfoSectionTitle: "Important: About your Ijazah Program",
        ijazahInfoSectionText: "Each session will be approximately 10-20 minutes. We will begin by improving your Tajwid with Juz' Amma. Once proficiency is achieved, we will commence with the Ijazah. If your Tajwid is already perfect, we will begin the Ijazah program immediately.",
        quizTimeLabel: "What time do you want to read?",
        quizQiraahLabel: "Which Qira'ah do you want to learn?",
        scrollNote: "Scroll to see all days",
        timeSlot1: "5:10 AM - 5:50 AM",
        timeSlot2: "6:20 PM - 7:10 PM",
        timeSlot3: "2:10 PM - 3:00 PM",
        timezoneNote: "(GMT+7 Jakarta Time)",
        quizLanguageLabel: "In which language do you want to learn?",
        langArabic: "Arabic",
        langEnglish: "English",
        langIndonesian: "Indonesian",
        summaryQiraah: "Preferred Qira'ah",
        summaryTime: "Preferred Time",
        summaryLanguage: "Language",
        ijazahTimeEstimationTitle: "Est. time:",
        hafsTime_1: "about 4–6 years",
        hafsTime_2: "about 2–3 years",
        hafsTime_3: "about 1.5–2 years",
        hafsTime_4: "about 1–1.5 years",
        hafsTime_5: "about 10–12 months",
        hafsTime_6: "about 8–10 months",
        hafsTime_7: "about 7–9 months",
        tenRecitationsTime: "Depends on your speed and readiness",
        ijazahTimeNoteSpeed: "might be less, depends on your speed",
        tajwidSectionTitle: "Improve Tajwid",
        tajwidSectionDesc: "Dedicated sessions to perfect your recitation.",
        tajwidButtonText: "Start Improving",
        tajwidQuizTitle: "Tajwid Improvement Session",
        tajwidLevelLabel: "How good are you in Tajwid?",
        tajwidLevelGood: "Good",
        tajwidLevelNotTooGood: "Not too good",
        tajwidLevelNormal: "Normal",
        tajwidLevelBad: "Bad",
        tajwidLevelReallyBad: "Really bad",
        subscriptionLengthLabel: "Choose the length",
        subscriptionOption15Days: "15 Days",
        subscriptionOption10Days: "10 Days",
        subscriptionOption5Days: "5 Days",
        priceDisplay: "Price: {price} IDR",
        teachersSectionTitle: "Our Teachers",
        teachersSectionDesc: "Meet our qualified and experienced teachers.",
        teachersButtonText: "Meet the Teachers",
        teachersPageTitle: "Our Teachers",
        teacherYamanName: "Qari Yaman Darwish",
        teacherYamanBio: "Hello, I am Yaman Darwish, a student at Imam Al-Shafi'i University. I will try to help you with all your Qur'an needs, insha'Allah",
        ijazahMemorizationTitle: "With or Without Memorization?",
        ijazahMemorizationSubtitle: "Do you want to memorize the Qur'an alongside your Ijazah, or focus only on recitation?",
        withMemorizationButton: "With Memorization (Tahfidh)",
        withoutMemorizationButton: "Recitation Only (Talaqqi)",
        summaryMemorization: "Memorization",
        summaryWithMemorization: "With Memorization",
        summaryWithoutMemorization: "Recitation Only",
        feedbackSectionTitle: "Feedback",
        feedbackSectionDesc: "Have a suggestion or found a bug? Let us know!",
        feedbackButtonText: "Give Feedback",
        feedbackPageTitle: "Share Your Feedback",
        feedbackPageSubtitle: "We value your input to improve our platform.",
        feedbackPlaceholder: "Type your suggestions, bug reports, or feedback here...",
        sendFeedbackButton: "Send Feedback",
        feedbackThanksMessage: "Feedback Received!",
        feedbackThanksText: "Thank you for helping us improve. We appreciate your contribution.",
        askAiPageTitle: "AI Assistant",
        askAiPageSubtitle: "Ask me anything about Maqra'at Al-Huda!",
        askAiPlaceholder: "Type your question...",
        askAiInitialMessage: "As-salamu alaykum! I'm the Maqra'at Al-Huda AI assistant. How can I help you today? You can ask about Ijazah programs, Tasmi' sessions, teachers, or anything else.",
        shareButtonText: "Share",
        copiedButtonText: "Copied!",
    },
    'ar': {
        headerTitle: "مقرأة الهدى",
        headerSubtitle: "بإشراف القارئ يمن درويش",
        heroTitle: "ابدأ رحلتك القرآنية",
        heroSubtitle: "أتقن فن التلاوة المقدس واربط نسبك بالنبي (ﷺ) من خلال برامج الإجازة المعتمدة، بتوجيه من القارئ يمن درويش.",
        heroButton: "ابدأ رحلتك",
        title: "تسجيل في دورة",
        subtitle: "احجز مقعدك وابدأ رحلتك التعليمية.",
        nameLabel: "الاسم الكامل",
        sourceLabel: "كيف سمعت عنا؟",
        aboutLabel: "أخبرنا عن نفسك",
        phoneLabel: "رقم الواتساب / للتواصل",
        whatsappLabel: "رقم الواتساب (تأكد من صحته)",
        buttonText: "إرسال التسجيل",
        homeButtonText: "الرئيسية",
        registerButtonText: "تسجيل",
        langButtonText: "EN",
        homePageTitle: "أهلاً بكم في مقرأة الهدى",
        homePageSubtitle: "نستكشف العلوم الإسلامية، معاً.",
        courseInfoText: "نحن بصدد إعداد دورات إسلامية نافعة.",
        followUsText: "سيتم فتح التسجيل عند الإعلان عن دورة جديدة.",
        instagramLinkText: "تابعنا على إنستغرام",
        previousCoursesBtnHomepage: "عرض الدورات السابقة",
        coursesTitle: "دوراتنا السابقة",
        course3Text: "أيها الولد",
        course4Text: "تحسين التلاوة",
        thanksMessage: "شكراً لك!",
        thanksText: "تم استلام طلبك. سنتواصل معك قريباً.",
        registerAnotherBtn: "تسجيل جديد",
        backToHome: "العودة للرئيسية",
        regClosedTitle: "التسجيل مغلق",
        regClosedText: "لا توجد دورات فعالة حالياً, يرجى العودة لاحقاً.",
        regClosedButton: "إغلاق",
        ijazahButtonText: "أريد إجازة",
        ijazahTitle: "ابدأ رحلتك في الإجازة القرآنية",
        ijazahSubtitle: "اربط سندك بالنبي صلى الله عليه وسلم. اختر طريقك:",
        hafsButton: "حفص عن عاصم",
        tenRecitationsButton: "القراءات العشر",
        differentQiraahButton: "قراءة مختلفة",
        quizTitle: "طلب إجازة",
        quizNameLabel: "الاسم الكامل:",
        quizAgeLabel: "العمر:",
        quizFromLabel: "بلد الإقامة:",
        quizWeeklyLabel: "الالتزام الأسبوعي بالقراءة:",
        quizSheikhLabel: "هل قرأت على شيخ من قبل؟",
        yes: "نعم",
        no: "لا",
        quizJourneyLabel: "صف باختصار رحلتك مع القرآن:",
        nextButton: "التالي",
        paymentTitle: "معلومات الدفع",
        paymentSubtitle: "يرجى تأكيد اختيارك للمتابعة.",
        ijazahSectionTitle: "برنامج الإجازة",
        ijazahSectionDesc: "اربط سندك المتصل.",
        tasmiSectionTitle: "تسميع مفتوح",
        tasmiSectionDesc: "اسمع حفظك للشيخ.",
        coursesSectionTitle: "الدورات السابقة",
        coursesSectionDesc: "تصفح الدورات التي قدمناها سابقاً.",
        aboutUsSectionTitle: "عنّا",
        aboutUsSectionDesc: "تعرف على المزيد حول رسالتنا ورؤيتنا.",
        aboutUsButtonText: "اعرف المزيد",
        aboutUsPageTitle: "عن مقرأة الهدى",
        aboutUsPageText: "هذا الموقع هو المنصة الرسمية لجميع برامجنا. هنا يمكنك:\n- التسجيل في برامج الإجازة في مختلف القراءات.\n- التسجيل في جلسات 'تحسين التلاوة' المخصصة.\n- طلب جلسة 'تسميع' مجانية لمراجعة الحفظ.\n- الاطلاع على دوراتنا السابقة والتعرف على رسالتنا.",
        tasmiButtonText: "أريد التسميع المفتوح",
        tasmiQuizTitle: "جلسة تسميع مفتوحة",
        tasmiPortionLabel: "الجزء أو السورة المراد تسميعها:",
        tasmiTimeLabel: "الوقت المفضل للجلسة:",
        submitButton: "إرسال الطلب",
        tasmiFatihahOption: "الفاتحة",
        tasmiJuzAmmaOption: "بعض من جزء عم",
        tasmiWeeklyLabel: "كم عدد الجلسات التي تريدها؟",
        tasmiInfoTitle: "ماذا بعد؟",
        tasmiInfoText1: "سيقوم الشيخ باختيار الوقت والتاريخ المتاح له.",
        tasmiInfoText2: "سنحاول الرد عليك في أسرع وقت ممكن.",
        paymentPriceText: "السعر سيكون:",
        payButton: "إرسال الطلب",
        bsiText: "أنت على بعد خطوة واحدة من بدء رحلتك",
        summaryTitle: "ملخص الطلب",
        summaryPath: "مسار الإجازة",
        summaryCommitment: "الالتزام الأسبوعي",
        summaryPrice: "السعر",
        monthlyText: "شهرياً",
        noteTitle: "ملاحظة:",
        noteText: "الجداول الزمنية تخضع لتوفر الشيخ.",
        changeIjazahButton: "تغيير إجازتي",
        youtubeLinkText: "شاهد على يوتيوب",
        moderatorText: "هذا الموقع تحت إشراف يمن بالكامل",
        daysPerWeek: "{count} أيام/أسبوع",
        ijazahPreviewCardTitle: "شهادة الإجازة",
        ijazahPreviewDesc: "شاهد عينة من شهادة الإجازة لدينا.",
        ijazahPreviewButtonText: "أرني إجازتكم",
        ijazahPreviewTitle: "معاينة الإجازة",
        ijazahSampleText: "شهادة الإجازة هذه تربط سند حاملها في تلاوة القرآن الكريم بالنبي محمد (صلى الله عليه وسلم). تُمنح للطالب بعد إتمام حفظ القرآن الكريم عن ظهر قلب وإظهار الإتقان في التجويد والتلاوة أمام شيخ مؤهل.",
        ijazahGrantText: "بفضل الله، أجازني سيدي الشيخ أحمد الكنس بالقراءات العشر الصغرى المتواترة عن رسول الله (صلى الله عليه وسلم).\n\nفي جامع الإمام الشافعي ليلة السابع عشر من رمضان،\nالموافق: 25 مارس 2024",
        tasmiInfoSectionTitle: "هام: بخصوص جلسة التسميع",
        tasmiInfoSectionText: "سيتم توفير المعلومات حول جلسة التسميع هنا. يرجى التحقق لاحقًا للحصول على التفاصيل.",
        continueButton: "متابعة",
        backButton: "رجوع",
        ijazahInfoRequirementsTitle: "معلومات ومتطلبات الإجازة",
        ijazahInfoSectionTitle: "هام: بخصوص برنامج الإجازة",
        ijazahInfoSectionText: "مدة كل جلسة ستكون حوالي 10-20 دقيقة. سنبدأ بتحسين تجويدك مع جزء عم. بمجرد تحقيق الإتقان، سنبدأ بالإجازة. إذا كان تجويدك متقناً بالفعل، فسنبدأ ببرنامج الإجازة على الفور.",
        quizTimeLabel: "في أي وقت تريد أن تقرأ؟",
        quizQiraahLabel: "أي قراءة تريد أن تتعلم؟",
        scrollNote: "مرر لرؤية كل الأيام",
        timeSlot1: "5:10 صباحًا - 5:50 صباحًا",
        timeSlot2: "6:20 مساءً - 7:10 مساءً",
        timeSlot3: "2:10 مساءً - 3:00 مساءً",
        timezoneNote: "(توقيت جاكرتا GMT+7)",
        quizLanguageLabel: "بأي لغة تريد أن تتعلم؟",
        langArabic: "العربية",
        langEnglish: "الإنجليزية",
        langIndonesian: "الإندونيسية",
        summaryQiraah: "القراءة المفضلة",
        summaryTime: "الوقت المفضل",
        summaryLanguage: "اللغة",
        ijazahTimeEstimationTitle: "الوقت التقديري:",
        hafsTime_1: "حوالي 4-6 سنوات",
        hafsTime_2: "حوالي 2-3 سنوات",
        hafsTime_3: "حوالي 1.5-2 سنة",
        hafsTime_4: "حوالي 1-1.5 سنة",
        hafsTime_5: "حوالي 10-12 شهرًا",
        hafsTime_6: "حوالي 8-10 أشهر",
        hafsTime_7: "حوالي 7-9 أشهر",
        tenRecitationsTime: "يعتمد على سرعتك واستعدادك",
        ijazahTimeNoteSpeed: "قد يكون أقل، يعتمد على سرعتك",
        tajwidSectionTitle: "تحسين التجويد",
        tajwidSectionDesc: "جلسات مخصصة لإتقان تلاوتك.",
        tajwidButtonText: "ابدأ التحسين",
        tajwidQuizTitle: "جلسة تحسين التجويد",
        tajwidLevelLabel: "ما مدى إتقانك للتجويد؟",
        tajwidLevelGood: "جيد",
        tajwidLevelNotTooGood: "ليس جيداً جداً",
        tajwidLevelNormal: "عادي",
        tajwidLevelBad: "سيئ",
        tajwidLevelReallyBad: "سيئ جداً",
        subscriptionLengthLabel: "اختر المدة",
        subscriptionOption15Days: "15 يومًا",
        subscriptionOption10Days: "10 أيام",
        subscriptionOption5Days: "5 أيام",
        priceDisplay: "السعر: {price} روبية إندونيسية",
        teachersSectionTitle: "مشايخنا",
        teachersSectionDesc: "تعرف على مشايخنا المؤهلين وذوي الخبرة.",
        teachersButtonText: "تعرف على المشايخ",
        teachersPageTitle: "مشايخنا",
        teacherYamanName: "القارئ يمن درويش",
        teacherYamanBio: "مرحباً، أنا يمن درويش، طالب في جامعة الإمام الشافعي. سأحاول مساعدتكم في كل ما تحتاجونه في القرآن، إن شاء الله",
        ijazahMemorizationTitle: "مع أو بدون حفظ؟",
        ijazahMemorizationSubtitle: "هل ترغب في حفظ القرآن بالتوازي مع الإجازة، أم التركيز على التلاوة فقط؟",
        withMemorizationButton: "مع الحفظ (تحفيظ)",
        withoutMemorizationButton: "تلاوة فقط (تلقي)",
        summaryMemorization: "الحفظ",
        summaryWithMemorization: "مع الحفظ",
        summaryWithoutMemorization: "تلاوة فقط",
        feedbackSectionTitle: "ملاحظات",
        feedbackSectionDesc: "هل لديك اقتراح أو وجدت خطأ؟ أخبرنا!",
        feedbackButtonText: "أرسل ملاحظاتك",
        feedbackPageTitle: "شاركنا ملاحظاتك",
        feedbackPageSubtitle: "نقدر مدخلاتك لتحسين منصتنا.",
        feedbackPlaceholder: "اكتب اقتراحاتك، تقارير الأخطاء، أو ملاحظاتك هنا...",
        sendFeedbackButton: "أرسل الملاحظات",
        feedbackThanksMessage: "تم استلام الملاحظات!",
        feedbackThanksText: "شكراً لمساعدتنا على التحسين. نحن نقدر مساهمتك.",
        askAiPageTitle: "المساعد الذكي",
        askAiPageSubtitle: "اسألني أي شيء عن مقرأة الهدى!",
        askAiPlaceholder: "اكتب سؤالك...",
        askAiInitialMessage: "السلام عليكم! أنا مساعد مقرأة الهدى الذكي. كيف يمكنني مساعدتك اليوم؟ يمكنك السؤال عن برامج الإجازة، جلسات التسميع، المشايخ، أو أي شيء آخر.",
        shareButtonText: "مشاركة",
        copiedButtonText: "تم النسخ!",
    },
    'id': {
        headerTitle: "Maqra'at Al-Huda",
        headerSubtitle: "Oleh Qari Yaman Darwish",
        heroTitle: "Mulailah Perjalanan Qur'an Anda",
        heroSubtitle: "Kuasai seni suci tilawah dan sambungkan silsilah Anda kepada Nabi (ﷺ) melalui program Ijazah bersertifikat, dibimbing oleh Qari Yaman Darwish.",
        heroButton: "Mulai Perjalanan Anda",
        title: "Pendaftaran Kursus",
        subtitle: "Amankan tempat Anda dan mulailah perjalanan belajar Anda.",
        nameLabel: "Nama Lengkap",
        sourceLabel: "Dari mana Anda mengetahui tentang kami?",
        aboutLabel: "Ceritakan tentang diri Anda",
        phoneLabel: "Nomor WhatsApp / Kontak",
        whatsappLabel: "Nomor WhatsApp (pastikan benar)",
        buttonText: "Kirim Pendaftaran",
        homeButtonText: "Beranda",
        registerButtonText: "Daftar",
        langButtonText: "ID",
        homePageTitle: "Selamat Datang di Maqra'at Al-Huda",
        homePageSubtitle: "Menjelajahi ilmu Islam, bersama-sama.",
        courseInfoText: "Kami sedang mempersiapkan kursus-kursus Islami yang berwawasan.",
        followUsText: "Pendaftaran akan dibuka saat kursus baru diumumkan.",
        instagramLinkText: "Ikuti di Instagram",
        previousCoursesBtnHomepage: "Lihat Kursus Sebelumnya",
        coursesTitle: "Kursus-Kursus Kami Sebelumnya",
        course3Text: "Ayyuhal Walad",
        course4Text: "Tahsin Tilawah (Memperbaiki Bacaan)",
        thanksMessage: "Terima Kasih!",
        thanksText: "Permintaan Anda telah dikirim. Kami akan segera menghubungi Anda.",
        registerAnotherBtn: "Daftar Lagi",
        backToHome: "Kembali ke Beranda",
        regClosedTitle: "Pendaftaran Ditutup",
        regClosedText: "Tidak ada kursus aktif saat ini, silakan kembali lagi nanti.",
        regClosedButton: "Tutup",
        ijazahButtonText: "Saya ingin Ijazah",
        ijazahTitle: "Mulailah Perjalanan Ijazah Anda",
        ijazahSubtitle: "Sambungkan sanad Anda kembali ke Nabi (SAW). Pilih jalan Anda:",
        hafsButton: "Hafs 'an 'Asim",
        tenRecitationsButton: "Qira'at Sepuluh",
        differentQiraahButton: "Qira'at yang Berbeda",
        quizTitle: "Aplikasi Ijazah",
        quizNameLabel: "Nama Lengkap:",
        quizAgeLabel: "Usia:",
        quizFromLabel: "Negara Tempat Tinggal:",
        quizWeeklyLabel: "Komitmen Membaca Mingguan:",
        quizSheikhLabel: "Apakah Anda pernah belajar dengan seorang Syekh sebelumnya?",
        yes: "Ya",
        no: "Tidak",
        quizJourneyLabel: "Jelaskan secara singkat perjalanan Anda dengan Al-Qur'an:",
        nextButton: "Selanjutnya",
        paymentTitle: "Informasi Pembayaran",
        paymentSubtitle: "Harap konfirmasi pilihan Anda untuk melanjutkan.",
        ijazahSectionTitle: "Program Ijazah",
        ijazahSectionDesc: "Sambungkan sanad transmisi Anda.",
        tasmiSectionTitle: "Tasmi' Terbuka",
        tasmiSectionDesc: "Setorkan hafalan Anda kepada seorang guru.",
        coursesSectionTitle: "Kursus Sebelumnya",
        coursesSectionDesc: "Jelajahi kursus-kursus yang pernah kami tawarkan.",
        aboutUsSectionTitle: "Tentang Kami",
        aboutUsSectionDesc: "Pelajari lebih lanjut tentang misi dan visi kami.",
        aboutUsButtonText: "Pelajari Lebih Lanjut",
        aboutUsPageTitle: "Tentang Maqra'at Al-Huda",
        aboutUsPageText: "Situs web ini adalah platform resmi untuk semua program kami. Di sini Anda dapat:\n- Mendaftar untuk program Ijazah dalam berbagai Qira'at.\n- Mendaftar untuk sesi 'Tahsin Tilawah' (Perbaikan Tajwid) khusus.\n- Meminta sesi 'Tasmi'' (penilaian bacaan) gratis.\n- Melihat kursus kami sebelumnya dan mempelajari misi kami.",
        tasmiButtonText: "Saya ingin Tasmi' terbuka",
        tasmiQuizTitle: "Sesi Tasmi' Terbuka",
        tasmiPortionLabel: "Juz' atau Surah yang akan Dibacakan:",
        tasmiTimeLabel: "Waktu yang Diinginkan untuk Sesi:",
        submitButton: "Kirim Permintaan",
        tasmiFatihahOption: "Al-Fatihah",
        tasmiJuzAmmaOption: "Beberapa dari Juz Amma",
        tasmiWeeklyLabel: "Berapa sesi yang Anda inginkan?",
        tasmiInfoTitle: "Apa Selanjutnya?",
        tasmiInfoText1: "Guru akan memilih waktu dan tanggal yang tersedia untuknya.",
        tasmiInfoText2: "Kami akan mencoba menjawab Anda secepat mungkin.",
        paymentPriceText: "Ini akan menjadi:",
        payButton: "Kirim Aplikasi",
        bsiText: "Anda selangkah lagi untuk memulai perjalanan Anda",
        summaryTitle: "Ringkasan Aplikasi",
        summaryPath: "Jalur Ijazah",
        summaryCommitment: "Komitmen Mingguan",
        summaryPrice: "Harga",
        monthlyText: "bulanan",
        noteTitle: "Catatan:",
        noteText: "Penjadwalan tergantung pada ketersediaan guru.",
        changeIjazahButton: "Ubah Ijazah saya",
        youtubeLinkText: "Tonton di YouTube",
        moderatorText: "Situs web ini sepenuhnya dimoderasi oleh Yaman",
        daysPerWeek: "{count} hari/minggu",
        ijazahPreviewCardTitle: "Sertifikat Ijazah",
        ijazahPreviewDesc: "Lihat contoh sertifikat Ijazah kami.",
        ijazahPreviewButtonText: "Tunjukkan Ijazah Anda",
        ijazahPreviewTitle: "Pratinjau Ijazah",
        ijazahSampleText: "Sertifikat Ijazah ini menghubungkan rantai transmisi (Sanad) pemegangnya untuk pembacaan Al-Qur'an kembali ke Nabi Muhammad (SAW). Diberikan kepada siswa setelah menyelesaikan hafalan Al-Qur'an dan menunjukkan penguasaan dalam Tajwid dan tilawah di hadapan seorang Syekh yang berkualitas.",
        ijazahGrantText: "Dengan rahmat Allah, guru saya Syekh Ahmed Al-Kanas memberi saya Ijazah dalam Sepuluh Qira'at Mutawatir Kecil dari Rasulullah (SAW).\n\nDi masjid Universitas Imam Al-Syafi'i pada malam ketujuh belas Ramadhan,\nBertepatan dengan: 25 Maret 2024",
        tasmiInfoSectionTitle: "Penting: Tentang Sesi Tasmi' Anda",
        tasmiInfoSectionText: "Informasi tentang sesi Tasmi' akan diberikan di sini. Silakan periksa kembali nanti untuk detailnya.",
        continueButton: "Lanjutkan",
        backButton: "Kembali",
        ijazahInfoRequirementsTitle: "Informasi dan Persyaratan Ijazah",
        ijazahInfoSectionTitle: "Penting: Tentang Program Ijazah Anda",
        ijazahInfoSectionText: "Setiap sesi akan berlangsung sekitar 10-20 menit. Kita akan mulai dengan memperbaiki Tajwid Anda dengan Juz' Amma. Setelah kemahiran tercapai, kita akan memulai Ijazah. Jika Tajwid Anda sudah sempurna, kita akan segera memulai program Ijazah.",
        quizTimeLabel: "Jam berapa Anda ingin membaca?",
        quizQiraahLabel: "Qira'ah mana yang ingin Anda pelajari?",
        scrollNote: "Gulir untuk melihat semua hari",
        timeSlot1: "05:10 - 05:50",
        timeSlot2: "18:20 - 19:10",
        timeSlot3: "14:10 - 15:00",
        timezoneNote: "(WIB, GMT+7 Waktu Jakarta)",
        quizLanguageLabel: "Dalam bahasa apa Anda ingin belajar?",
        langArabic: "Arab",
        langEnglish: "Inggris",
        langIndonesian: "Indonesia",
        summaryQiraah: "Qira'ah Pilihan",
        summaryTime: "Waktu Pilihan",
        summaryLanguage: "Bahasa",
        ijazahTimeEstimationTitle: "Perkiraan waktu:",
        hafsTime_1: "sekitar 4–6 tahun",
        hafsTime_2: "sekitar 2–3 tahun",
        hafsTime_3: "sekitar 1.5–2 tahun",
        hafsTime_4: "sekitar 1–1.5 tahun",
        hafsTime_5: "sekitar 10–12 bulan",
        hafsTime_6: "sekitar 8–10 bulan",
        hafsTime_7: "sekitar 7–9 bulan",
        tenRecitationsTime: "Tergantung pada kecepatan dan kesiapan Anda",
        ijazahTimeNoteSpeed: "bisa jadi kurang, tergantung kecepatan Anda",
        tajwidSectionTitle: "Perbaiki Tajwid",
        tajwidSectionDesc: "Sesi khusus untuk menyempurnakan bacaan Anda.",
        tajwidButtonText: "Mulai Perbaikan",
        tajwidQuizTitle: "Sesi Perbaikan Tajwid",
        tajwidLevelLabel: "Seberapa baik Anda dalam Tajwid?",
        tajwidLevelGood: "Baik",
        tajwidLevelNotTooGood: "Kurang baik",
        tajwidLevelNormal: "Biasa",
        tajwidLevelBad: "Buruk",
        tajwidLevelReallyBad: "Sangat buruk",
        subscriptionLengthLabel: "Pilih durasi",
        subscriptionOption15Days: "15 Hari",
        subscriptionOption10Days: "10 Hari",
        subscriptionOption5Days: "5 Hari",
        priceDisplay: "Harga: {price} IDR",
        teachersSectionTitle: "Guru Kami",
        teachersSectionDesc: "Temui guru-guru kami yang berkualitas dan berpengalaman.",
        teachersButtonText: "Temui Guru",
        teachersPageTitle: "Guru Kami",
        teacherYamanName: "Qari Yaman Darwish",
        teacherYamanBio: "Halo, saya Yaman Darwish, seorang mahasiswa di Universitas Imam Al-Syafi'i. Saya akan mencoba membantu Anda dengan semua kebutuhan Al-Qur'an Anda, insya'Allah",
        ijazahMemorizationTitle: "Dengan atau Tanpa Hafalan?",
        ijazahMemorizationSubtitle: "Apakah Anda ingin menghafal Al-Qur'an bersamaan dengan Ijazah Anda, atau hanya fokus pada tilawah?",
        withMemorizationButton: "Dengan Hafalan (Tahfidh)",
        withoutMemorizationButton: "Hanya Tilawah (Talaqqi)",
        summaryMemorization: "Hafalan",
        summaryWithMemorization: "Dengan Hafalan",
        summaryWithoutMemorization: "Hanya Tilawah",
        feedbackSectionTitle: "Umpan Balik",
        feedbackSectionDesc: "Punya saran atau menemukan bug? Beri tahu kami!",
        feedbackButtonText: "Beri Umpan Balik",
        feedbackPageTitle: "Bagikan Umpan Balik Anda",
        feedbackPageSubtitle: "Kami menghargai masukan Anda untuk meningkatkan platform kami.",
        feedbackPlaceholder: "Ketik saran, laporan bug, atau umpan balik Anda di sini...",
        sendFeedbackButton: "Kirim Umpan Balik",
        feedbackThanksMessage: "Umpan Balik Diterima!",
        feedbackThanksText: "Terima kasih telah membantu kami menjadi lebih baik. Kami menghargai kontribusi Anda.",
        askAiPageTitle: "Asisten AI",
        askAiPageSubtitle: "Tanyakan apa saja tentang Maqra'at Al-Huda!",
        askAiPlaceholder: "Ketik pertanyaan Anda...",
        askAiInitialMessage: "Assalamualaikum! Saya adalah asisten AI Maqra'at Al-Huda. Ada yang bisa saya bantu hari ini? Anda bisa bertanya tentang program Ijazah, sesi Tasmi', para guru, atau hal lainnya.",
        shareButtonText: "Bagikan",
        copiedButtonText: "Tersalin!",
    }
};